### ISSUE TITLE
Add Linux RAID and SMART monitoring

### ISSUE THREAD

**Issue by huksley** [afaqurk/linux-dash#228]
Parse /proc/mdstat
and 
smartctl -H <disk> 
For HDD health information

**Comment by scvnc** [comment]
:+1:  This would be my favorite feature.  

Why was this task closed?  It's not clear to me if this was implemented. Any progress on it? Anyone working on it? I'll offer to write a module.

**Comment by miquelbotanch** [comment]
+1

It would be very nice to show if it's degraded or ok, and spare disks...

El 11/03/2015, a les 18:10, Vincent Schramer <notifications@github.com> va escriure:
