### ISSUE TITLE
Add cron jobs: feature request

### ISSUE THREAD

**Issue by hyptos** [afaqurk/linux-dash#232]
Hi, 

As an enhancement, it would be nice to see the last cron jobs or the five last cron jobs with the time of execution :).

Like a table with the date and time of execution, the user who executed it and the name of the filed executed.

We can get the logs of cron jobs with this commands.

```
grep CRON /var/log/syslog
```
Linux dash is running smoothly on my VPS on DigitalOcean thanks :)

**Comment by afaqurk** [comment]
One step closer. There is now a module which shows all cron jobs scheduled on the server.

[http://linuxdash.afaqtariq.com/#/basic-info](http://linuxdash.afaqtariq.com/#/basic-info)

**Comment by hyptos** [comment]
Great thanks :+1:

**Comment by afaqurk** [comment]
Very basic Cron History module added to [Basic Info page](http://linux-dash.dev/#/basic-info). 

Currently limited to the first 50 results in `/var/log/syslog`.

We need a better way to support multiple Linux flavors and their respective possible cron log files. I'm open to suggestions/PRs.
