### ISSUE TITLE
Use semicolon instead of coma as separator in libs/Modules/df.php

### ISSUE THREAD

**Issue by piernov** [afaqurk/linux-dash#249]
In many languages, coma is used as decimal separator in numbers. Therefore, if the output of `df -Ph` is localized, chances are it will output numbers with coma separator (`1,8T` for example), thus breaking the following `explode(',', …)`.
A solution would be to replace coma with semicolon in the `awk` script and in the `explode()` call.
Patch below:
```diff
diff --git a/libs/Modules/df.php b/libs/Modules/df.php
index d1799a1..3538392 100644
--- a/libs/Modules/df.php
+++ b/libs/Modules/df.php
@@ -7,7 +7,7 @@

         public function getData($args=array()) {

-            exec('/bin/df -Ph | awk \'BEGIN {OFS=","} {print $1,$2,$3,$4,$5,$6}\'', $result);
+            exec('/bin/df -Ph | awk \'BEGIN {OFS=";"} {print $1,$2,$3,$4,$5,$6}\'', $result);

             $data = array();

@@ -17,7 +17,7 @@
                     $x++;
                     continue;
                 }
-                $data[] = explode(',', $result[$x]);
+                $data[] = explode(';', $result[$x]);

                 unset($result[$x], $a);
                 $x++;
```

**Comment by afaqurk** [comment]
This should no longer be an issue as of the latest release. The server/modules/shell_files/disk_paritions.sh file now constructs and a JSON string, like all other module shell files.
