### ISSUE TITLE
Breakdown by vhost: feature request

### ISSUE THREAD

**Issue by marcusatbang** [afaqurk/linux-dash#256]
When a single web server is hosting several websites using virtual hosts (with Apache, NginX etc) one of the biggest missing pieces in monitoring is the ability to establish _which_ of the sites is contributing most to the current load (CPU, memory use, number of processes etc). Most solutions for inspecting the internals of Apache are log-based, but the standard Apache log format (which NginX uses as well) doesn't by default include the vhost name, only the request URI beginning with `/`.

The only reliable way of establishing which virtual host is contributing to server load with Apache - that I'm aware of - is with `mod_status`, which displays a list o. This ties process IDs to the URLs they are serving, and the immediate process status. It works, but it's not pretty.

![mod_status](http://www.serverwatch.com/img/apachemaint.gif)

It would make `linux-dash` incredibly useful if it was possible to show a table of domain names / virtual hosts and the CPU, memory etc that each is consuming (aggregated over all the relevant processes).

The most practical way of achieving this for Apache is to parse the output of `mod_status`. I don't know of a good way to achieve the same for NginX, Varnish or other web servers.

**Comment by afaqurk** [comment]
Thanks for the idea. It seems quite useful but difficult to accomplish consistently across web servers. Especially for very high traffic time periods, this feature would be an added load on the system, creating a variation of the [Observer effect](http://en.wikipedia.org/wiki/Observer_effect_(physics)) for web apps.

If you would like to submit a pull request to add some subset of this functionality, I am sure it would be most welcome.
