### ISSUE TITLE
bandwidth widget only works for one interface

### ISSUE THREAD

**Issue by d1c3** [afaqurk/linux-dash#268]
I'm running linux-dash on archlinux-arm on RaspberryPi. It is connected to network through wlan.
The bandwidth widget only shows eth0 although I have eth0 and wlan0 as interfaces in /sys/class/net.
```
$ ls /sys/class/net
eth0  lo  wlan0
```

**Comment by Fuxy22** [comment]
Is this still an issue in the latest version? 

Looking at the code this shouldn't be a issue anymore.

**Comment by d1c3** [comment]
works
