### ISSUE TITLE
Multiple Hosts

### ISSUE THREAD

**Issue by codex73** [afaqurk/linux-dash#272]
Not sure if you'd like to add functionality to switch hosts maybe with a dropdown or links. I'd love to help with this if you'd think it a good addition. For example, I manage about 30 servers, with a drop-down I'd be able to switch between all.

**Comment by afaqurk** [comment]
**Will there be support for multiple servers?**

Yes. After version 2.0 is reached, a fork will be created to work on a multiple-server version of linux dash. This has been a long time coming.

**Will be a dropdown with a long list of servers (persumably pulled from a config file)?**

No. If you need this functionality, please fork the project. 

**How will the multi-server version of linux dash work?**

Not entirely sure of that yet. At first glance, it seems most appropriate to have a client on each machine and a server which aggregates the data. This adds several application design complexities which need to be handled. Again, this is mere conjecture until linux dash reaches v2.0 and a separate project is created to focus on a multi-server application.

P.S. Goals for v2.0 are in the README.
