### ISSUE TITLE
Apache Log: sh: 1: /usr/bin/grep: not found

### ISSUE THREAD

**Issue by christianwgd** [afaqurk/linux-dash#274]
Hi, 

maybe this is a problem of my configuration, but if i view the "system status"-page, there is a log of this type every half second in my apache error log saying there's no /usr/bin/grep. I run ubuntu 14.04 and there is only a /bin/grep and no /usr/bin/grep. 

Thanks, 
Christian

**Comment by afaqurk** [comment]
Thanks for reporting this.
