### ISSUE TITLE
Strongswan module: feature request

### ISSUE THREAD

**Issue by evmuc** [afaqurk/linux-dash#276]
Would it be possible to add an overview of strongswan and the open connections?

**Comment by afaqurk** [comment]
I have never heard of strongswan so I am not able to help you on this front. I will label this as a feature request and hopefully another linux dash dev will be able to help you out.

And as always, it is quite easy to integrate any data available via the OS (CLI) or even through an external API into a linux dash widget. If you are familiar with how to obtain the data you would like to view, feel free to make an attempt and ask questions on here or on the linux dash [gitter](https://gitter.im/afaqurk/linux-dash). 

And remember, Pull requests > feature requests.
