### ISSUE TITLE
No information shows up. Nginx

### ISSUE THREAD

**Issue by HaoZeke** [afaqurk/linux-dash#280]
I used the gist config provided, but everything is blank with only the spinners moving.

**Comment by afaqurk** [comment]
This sounds like an issue with php5-fpm setup. The NGINX setup is confirmed to work. The [demo](linuxdash.afaqtariq.com) actually runs on nginx / php5-fpm.

For generic support, please go to the gitter for this project: (https://gitter.im/afaqurk/linux-dash)[https://gitter.im/afaqurk/linux-dash]
