### ISSUE TITLE
Master replaced and history gone.

### ISSUE THREAD

**Issue by rdebath** [afaqurk/linux-dash#282]
You seem to have broken your history chain within git, the current master is detached from the old master and the V1 and Alpha releases.

This doesn't look intentional, so I'm asking the question: do you intend to delete these nearly 500 commits ...
https://github.com/afaqurk/linux-dash/tree/8b8435e1c76154fd0a5c1ebe89f13c56a365c851

**Comment by afaqurk** [comment]
![](http://media1.giphy.com/media/lNHMPbRz6IhKU/200.gif)

Not intentional at all. It is a symptom of a regretful and mistaken use of `git push --force` on my part.

I need help rectifying this so any suggestions are welcomed. Losing 500 commits worth of history is not an option for me.

**Comment by rdebath** [comment]
Okay, first, don't panic, in the very worst case I have the 479 commits from 8b8435e1c76154fd0a5c1ebe89f13c56a365c851 back, but there's a gap so it's not perfect.

It's almost certain that you still have all those commits in your repository, git hates to delete stuff and it's difficult to purge anything less that 90days old. 

This is the URL you need:
http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery

and the first command to look at is "git reflog".

**Comment by rdebath** [comment]
Within the history from git-reflog you need to go back to the master as it was just before you broke it. You can do a git-log or git-checkout on any of the references you see in the reflog do investigate if they are the correct one.

There are quite a few ways of resetting the master to that commit; the normally recommended one is to use "git reset --hard".

You then will want to recover the 16 patches that you've got here (plus anything you haven't pushed yet). I think you can do that with "git rebase" using the "--onto" option. Another option is to use "git format-patch" to convert those commits into 16 files and then pull them back in using "git am". 

Any other questions ?

**Comment by rdebath** [comment]
And I've pushed the 'worst case' chain to 
Repo 
>   git@github.com:rdebath/test.git  

branch
>   afaqurk-linux-dash

**Comment by afaqurk** [comment]
Turns out I no longer have the reflog going back that far. I recently got a new machine and I only have the new, broken git history.

I tried to checkout the commit before the history was broken with no luck.

How did you get a copy of Linux Dash from before the history was broken to that 'worst case' branch on your repo?

**Comment by afaqurk** [comment]
@rdebath Your pull request worked. A BIG thank you for resolving this issue for the project.

Valuable lessons learned from this ordeal:

1. Don't ever use --force with push
2. Learn more about Git

**Comment by afaqurk** [comment]
@rdebath FYI - what you taught me also helped one of my colleagues at work during a rebase accident.

Thanks again!

**Comment by rdebath** [comment]
You're welcome... 

BTW: In answer to your earlier question; in the end I got the history from your guthub repo with

    git clone --mirror https://github.com/afaqurk/linux-dash.git

The "--mirror" gets the refs for the pull requests too. It was more recent than the one I pulled a few weeks before.
