### ISSUE TITLE
Confusing CPU LOAD on Raspbian

### ISSUE THREAD

**Issue by ChristianKrausse** [afaqurk/linux-dash#283]
The CPU LOAD displays 1 Min Avg values about 170%  while top on the system show something near 11%. Question: CPU LOAD over 100% seem to be strange, how could this be true?

**Comment by arnaudbey** [comment]
Hey. This is quite normal. More than 1 means that you have waiting processes 
This article explains this http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages
