### ISSUE TITLE
Request: Less obtrusive load indicator

### ISSUE THREAD

**Issue by IwfY** [afaqurk/linux-dash#284]
I'm using v1.5.

I find the load animation too obtrusive. It's hard to concentrate on other widgets if there is just one of these spinning circles. Some uniformly moving animation would be great. If there is no data available it should stop too.

**Comment by afaqurk** [comment]
latest commit adds new loader to make it less jarring.

Otherwise, having individual loaders for each module is a deliberate UX choice.
