### ISSUE TITLE
Angularjs javascript errors running on debian squeeze nas

### ISSUE THREAD

**Issue by intraxit** [afaqurk/linux-dash#289]
Thanks for your efforts on linux dash.
I installed it on my nas (debian squeeze). I get no data in the widgets and browser console reports angularjs ngrepeat duplicate javascript errors.
Is debian squeeze not supported?
Could this be solved and if yes how?

**Comment by intraxit** [comment]
Hey,

Debian squeeze is supported. I have never seen this error before. But it should be easily remedied if we can find exactly what line of the code it is taking place in.

Could you screenshot the error or copy and paste it in an email to me?

Also let me know what the exact url of the page was where you got the error.


--
Sincerely,
Afaq Tariq

**Comment by intraxit** [comment]
Hi,

Thanks your reply.

I add the error output of my browser console below:

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fram-chart.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fcpu-load.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fdisk-space.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fapp%2Ftable-data-plugin.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fsections%2Fbasic-info.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fram-chart.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fcpu-load.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fmodules%2Fdisk-space.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [$compile:tpload] http://errors.angularjs.org/1.3.4/$compile/tpload?p0=templates%2Fapp%2Ftable-data-plugin.html
z/<@http://10.0.0.80/js/angular.min.js:6:416
d/<@http://10.0.0.80/js/angular.min.js:136:70
f/<@http://10.0.0.80/js/angular.min.js:111:182
Me/this.$get</k.prototype.$eval@http://10.0.0.80/js/angular.min.js:125:36
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:119
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</e@http://10.0.0.80/js/angular.min.js:86:120
" angular.min.js:101

"Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=partition%20in%20diskSpaceData&p1=string%3AT&p2=T
z/<@http://10.0.0.80/js/angular.min.js:6:416
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:234:262
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20%7C%20filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%0A&p2=%0A
z/<@http://10.0.0.80/js/angular.min.js:6:416
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:234:262
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

So I see two category errors:
1. Error: [$compile:tpload]
2. Error: [ngRepeat:dupes]


What is wrong here?

Kind regards,

**Comment by intraxit** [comment]
So, there are two issues here, like you mentioned.

The dupes error is easily fixable by adding a single line to the JS. I suggest doing that first.

     Simply open up templates/modules/disk-space.html in an editor & go to line 19. It should look like this.
     Add "track by $index" to the ng-repeat part so it looks like this: ng-repeat="partition in diskSpaceData track by $index"
     Then do the same to the ng-repeat on line 28 in templates/app/table-data-plugin.html
        It should now look like this: ng-repeat="row in tableRows | filter:keyword | orderBy: sortByColumn track by $index"

Then reload the page and that error should now be gone.

The $compile:tpload error means that your templates folder isn't accessible. This can be for a number of reasons. If it is still an issue after you fixed the dupes error, try to load this template in the browser: [your-linux-dash-server]/templates/modules/disk-space.html
You should get a result similar to this. If you don't let me know what kind of error you get and we can debug from there.

Also, I recommend that you open a Github issue or use the gitter chat. That way other people who might have an issue like yours would also benefit from seeing the solution.

--
Sincerely,
Afaq Tariq

**Comment by intraxit** [comment]
Hi,

I added the "track by $index" to:
templates/modules/disk-space.html line 19 and templates/app/table-data-plugin.html line 28 and now have following errors:

Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'used'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
H/<@http://10.0.0.80/js/angular.min.js:58:63
r@http://10.0.0.80/js/angular.min.js:7:406
H@http://10.0.0.80/js/angular.min.js:57:394
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'avail'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
H/<@http://10.0.0.80/js/angular.min.js:58:63
r@http://10.0.0.80/js/angular.min.js:7:406
H@http://10.0.0.80/js/angular.min.js:57:394
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'avail'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
S/<.compile/<.pre@http://10.0.0.80/js/angular.min.js:68:372
Z@http://10.0.0.80/js/angular.min.js:70:89
H@http://10.0.0.80/js/angular.min.js:59:68
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'used'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
S/<.compile/<.pre@http://10.0.0.80/js/angular.min.js:68:372
Z@http://10.0.0.80/js/angular.min.js:70:89
H@http://10.0.0.80/js/angular.min.js:59:68
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'used'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
H/<@http://10.0.0.80/js/angular.min.js:58:63
r@http://10.0.0.80/js/angular.min.js:7:406
H@http://10.0.0.80/js/angular.min.js:57:394
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'avail'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
H/<@http://10.0.0.80/js/angular.min.js:58:63
r@http://10.0.0.80/js/angular.min.js:7:406
H@http://10.0.0.80/js/angular.min.js:57:394
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'avail'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
S/<.compile/<.pre@http://10.0.0.80/js/angular.min.js:68:372
Z@http://10.0.0.80/js/angular.min.js:70:89
H@http://10.0.0.80/js/angular.min.js:59:68
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69
" angular.min.js:101

"Error: [$interpolate:interr] http://errors.angularjs.org/1.3.4/$interpolate/interr?p0=%7B%7B%20getKB(partition%5B'used'%5D)%20%7D%7D&p1=TypeError%3A%20stringSize.slice%20is%20undefined
z/<@http://10.0.0.80/js/angular.min.js:6:416
g/<@http://10.0.0.80/js/angular.min.js:88:373
S/<.compile/<.pre@http://10.0.0.80/js/angular.min.js:68:372
Z@http://10.0.0.80/js/angular.min.js:70:89
H@http://10.0.0.80/js/angular.min.js:59:68
G/<@http://10.0.0.80/js/angular.min.js:66:289
g@http://10.0.0.80/js/angular.min.js:51:299
g@http://10.0.0.80/js/angular.min.js:51:316
g@http://10.0.0.80/js/angular.min.js:51:316
B/<@http://10.0.0.80/js/angular.min.js:50:414
L/<@http://10.0.0.80/js/angular.min.js:52:283
k@http://10.0.0.80/js/angular.min.js:56:347
ke</<.compile/</<@http://10.0.0.80/js/angular.min.js:235:148
Me/this.$get</k.prototype.$watchCollection/<@http://10.0.0.80/js/angular.min.js:121:305
Me/this.$get</k.prototype.$digest@http://10.0.0.80/js/angular.min.js:122:366
Me/this.$get</k.prototype.$apply@http://10.0.0.80/js/angular.min.js:125:305
m@http://10.0.0.80/js/angular.min.js:80:453
N@http://10.0.0.80/js/angular.min.js:85:32
tf/</w.onload@http://10.0.0.80/js/angular.min.js:86:69

The output of [your-linux-dash-server]/templates/modules/disk-space.html is as you described...

Any ideas?

rgds.,

**Comment by afaqurk** [comment]
It might be because you're not getting any data back from the server. 

Can you try going to:`[your-linux-dash-server//server/?module=general_info` and post the results? You should get a result similar to: http://linuxdash.afaqtariq.com/server/?module=general_info

Also, are **any** of the modules showing data on Linux Dash page?

**Comment by intraxit** [comment]
I was not getting data back from the server because of my php config was not allowing php parsing from the /server directory. I have now solved this.
I'm now getting data but still a lot of the dashboard widgets are not displaying any data.
On system status I only have cpu-load graph.... rest is trying to load data:
On basic info NOT CPU-info and I/o-stats...
On network NOT arp-cache table...
On accounts NOTHING...
On apps NOTHING...
Error: serverResponseData[0] is undefined
This is turning to be somewhat of a PIA !
Normally I'm using gkrellm and conky, which give me instant dashboard displays that are updated in real time, so your dashboard needs to improve quite a lot to get into the league of before mentioned apps.
But anyway thanks for your help!
rgds

**Comment by afaqurk** [comment]
The entire issue up until now has been incorrect configuration for PHP on the server. It is unfair to characterize that as a PIA on the part of Linux Dash.

Linux Dash seems to be doing what it is supposed to do. If you are interested in further help, let me know.
