### ISSUE TITLE
old theme in the current version

### ISSUE THREAD

**Issue by rigonijunior** [afaqurk/linux-dash#294]
How can I get the old theme in the current version.

![image](https://cloud.githubusercontent.com/assets/7538133/6434192/3d6b5008-c062-11e4-804d-b3293fe68200.png)

**Comment by afaqurk** [comment]
Sorry, new version no longer uses Bootstrap and therefore the old bootstrap theme is no longer available.

The current CSS is completely custom. If you are really motivated to get the old theme, you can try to manually code a cross-over theme using the new CSS structure and the [old bootstrap theme](http://egrappler.com/templatevamp-free-twitter-bootstrap-admin-template/).
