### ISSUE TITLE
Redis data not queried when Redis requires authentication

### ISSUE THREAD

**Issue by Aurielle** [afaqurk/linux-dash#297]
The `redis-cli INFO` command fails with `NOAUTH Authentication required.` if the Redis installation is set to require password authentication.

**Comment by afaqurk** [comment]
That is a good point. I'm not sure how to tackle this. Having Linux Dash ask for the Redis password in a config file is just horrible. 

Anyone else have any ideas on how to elegantly handle getting redis-cli info when auth is enabled?

**Comment by afaqurk** [comment]
For now, I have provided a config variable inside `/server/modules/shell_files/redis.sh` of Linux Dash for the user to provide their password. It assumes no password by default.

Not entirely happy with the implementation but it works for those eager to see redis info. I really hope someone finds a better way to do this.
