### ISSUE TITLE
Migrate for Golang and Beego ?

### ISSUE THREAD

**Issue by jniltinho** [afaqurk/linux-dash#299]
Migrate APP for Golang and Beego Framework, simple, fast
No Apache, No NodeJS, No PHP, No Python, No Composer, http built

http://beego.me/
http://beego.me/video
https://www.youtube.com/watch?v=w7RziV_Sn-g
Sqlite:
http://beego.me/docs/mvc/model/orm.md

Redis:
http://beego.me/docs/module/cache.md
https://github.com/astaxie/beego/blob/master/cache/redis/redis.go

http://hobbyisthacker.com/

**Comment by afaqurk** [comment]
Thanks for the suggestion. After looking into beego, it seems like serious overkill.  Linux Dash only requires the backend language to be a router to bash files. No need for a framework for such a specific, single-purpose task.
