### ISSUE TITLE
External IP address not formatted correctly

### ISSUE THREAD

**Issue by souvik1997** [afaqurk/linux-dash#300]
On the Network tab, the external IP address is not formatted correctly. The other IP addresses are formatted correctly. 

![screenshot from 2015-03-23 16 37 43](https://cloud.githubusercontent.com/assets/1762088/6791151/fa09b0a0-d17a-11e4-8dee-4c2b79dcf200.png)

**Comment by afaqurk** [comment]
Thank you for bringing this to my attention. It should be fixed now. Let me know if the update works for you.
