### ISSUE TITLE
Feature Request: Traffic Chart

### ISSUE THREAD

**Issue by evook** [afaqurk/linux-dash#301]
Hi,
It would be incredible nice to have a chart for the transferrate, like you have for ram and cpu.

$eth=`ls /sys/class/net | sed -e 's/^\(.*\)$/\1/'`

printf %s "$eth" | while IFS= read -r line
do
        in1=`cat /sys/class/net/$line/statistics/rx_bytes`
        out1=`cat /sys/class/net/$line/statistics/tx_bytes`
        sleep 1
        in2=`cat /sys/class/net/$line/statistics/rx_bytes`
        out2=`cat /sys/class/net/$line/statistics/tx_bytes`
        out_bytes=`expr $out2 - $out1`
        in_bytes=`expr $in2 - $in1`
        out_kbytes=`expr $out_bytes / 1024`
        in_kbytes=`expr $in_bytes / 1024`
done

Have you ever thought about something like this?

**Comment by afaqurk** [comment]
Have you taken a look at the Bandwidth module on the [Network tab](http://linuxdash.afaqtariq.com/#/network) of Linux Dash?

Is there any overlap in what you are looking for and that module?

**Comment by evook** [comment]
Thanks for replying. The bandwith sum is useful,and my feature request is rather of an aesthetic kind. The overlap would be the data input stream. If you subtract the value 1 second ago from the at the at moment value. You would have a value able to display in a smoothie.js chart. I hope that makes my enhancement request more understandable. Thank you.

**Comment by afaqurk** [comment]
Added. Please take a look and provide feedback if you can. It definitely could use some more tweaks for a smoother display.

**Comment by evook** [comment]
Hi, sorry for the late response. I was a little bit busy. It looks pretty nice and as expected. One thing I am wondering about is why scope.delay isn't honored when defined in modules.js .

If I increase the global delay in linuxDash.js the chart runs smooth, but also delays every other chart. Maybe you have an idea you to share before I start investing time. But thank you anyway. Keep on the good work.
