### ISSUE TITLE
Network tabs hangs with tor server

### ISSUE THREAD

**Issue by svengo** [afaqurk/linux-dash#303]
Hi,
every time I open the network tab, the web browser crashes.  
I think it happens because of the tor server process on my box.  Tor is preventing system utilities like netstat and lsof from working unless  `DisableDebuggerAttachment 1` is set (see https://trac.torproject.org/projects/tor/ticket/3313 for more information).

Is it possible to make the network tab not crash?

**Comment by afaqurk** [comment]
Hmmm. I have no idea why anything relating to a Tor issue would cause the network tab to crash. But then again, I don't use Tor.

If you hop on the [Linux Dash Gitter channel](https://gitter.im/afaqurk/linux-dash), I'd be happy to help you debug this.

First things first, could you please open up your web inspector console in chrome and paste any snapshot of the errors you might be able to grab before the tab crashes. It would be very useful to know what is exactly conflicting with the Tor bug before we go debugging the code. Feel free to paste the info here or better yet, in the gitter channel.

**Comment by svengo** [comment]
Here is the developer tools screenshot:
![Developer tools screenshot](https://cloud.githubusercontent.com/assets/2502366/7120300/775ae3f2-e20c-11e4-9b4f-cc1f9f185c7e.png)

It was just speculation that tor is the reason. I've clocked some commands from the linux-dash on console:
```bash
sven@umbar:/srv/www/umbar.svengo.net/linux-dash$ time netstat -ntu > /dev/null

real    0m0.089s
user    0m0.052s
sys     0m0.036s
sven@umbar:/srv/www/umbar.svengo.net/linux-dash$ time server/modules/python_files/speedtest_cli.py > /dev/null

real    0m18.176s
user    0m1.805s
sys     0m1.605s
sven@umbar:/srv/www/umbar.svengo.net/linux-dash$ time server/modules/shell_files/network_connections.sh > /dev/null

real    0m0.168s
user    0m0.098s
sys     0m0.078s
sven@umbar:/srv/www/umbar.svengo.net/linux-dash$ time server/modules/shell_files/ping.sh > /dev/null

real    0m4.278s
user    0m0.007s
sys     0m0.055s
```
No idea...

**Comment by afaqurk** [comment]
Any luck finding the root cause?

**Comment by svengo** [comment]
I have no idea where I should look. If I find something out I will let you know.

**Comment by afaqurk** [comment]
Sorry I can't help further. Really seems like an odd issue. Please let me know if and when you have a theory for the cause.
