### ISSUE TITLE
Installation instructions not clear

### ISSUE THREAD

**Issue by mgutt** [afaqurk/linux-dash#304]
I found several websites where Linux Dash was explained as easy to install tool. Copy and go to the folder and fine.. but thats not working for me. All graphs are empty and the JS error console says:
<pre><code>TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at http://www.example.com/admin/monitor/js/linuxDash.js:395:40
    at http://www.example.com/admin/monitor/js/linuxDash.js:60:20
    at http://www.example.com/admin/monitor/js/angular.min.js:111:182
    at k.$get.k.$eval (http://www.example.com/admin/monitor/js/angular.min.js:125:40)
    at k.$get.k.$digest (http://www.example.com/admin/monitor/js/angular.min.js:122:127)
    at k.$get.k.$apply (http://www.example.com/admin/monitor/js/angular.min.js:125:307)
    at m (http://www.example.com/admin/monitor/js/angular.min.js:80:455)
    at N (http://www.example.com/admin/monitor/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://www.example.com/admin/monitor/js/angular.min.js:86:69)
14angular.min.js:101 TypeError: Cannot read property '1_min_avg' of undefined
    at Object.scope.loadMetrics.generate (http://www.example.com/admin/monitor/js/modules.js:102:53)
    at http://www.example.com/admin/monitor/js/linuxDash.js:425:48
    at Array.forEach (native)
    at http://www.example.com/admin/monitor/js/linuxDash.js:424:31
    at http://www.example.com/admin/monitor/js/linuxDash.js:60:20
    at http://www.example.com/admin/monitor/js/angular.min.js:111:182
    at k.$get.k.$eval (http://www.example.com/admin/monitor/js/angular.min.js:125:40)
    at k.$get.k.$digest (http://www.example.com/admin/monitor/js/angular.min.js:122:127)
    at k.$get.k.$apply (http://www.example.com/admin/monitor/js/angular.min.js:125:307)
    at m (http://www.example.com/admin/monitor/js/angular.min.js:80:455)</code></pre>

I'm using PHP, Debian and Apache. I'm not a root user, but I'm able to use exec() etc. But I don't know if all necessary linux commands are available.

I tried to load http://www.example.com/admin/monitor/server/?module=load_avg but it displayed an empty page. I looked into the /server/index.php and tried the following through Putty:
<pre><code>example@example:~$ load_avg
-bash: load_avg: command not found
example@example:~$ modules/shell_files/load_avg
-bash: modules/shell_files/load_avg: No such file or directory
example@example:~$ cd /
example@example:/$ dir
bin   etc         lib         media  proc  sbin     sys  var
boot  home        lib64       mnt    root  selinux  tmp  vmlinuz
dev   initrd.img  lost+found  opt    run   srv      usr
example@example:/$</code></pre>

Does it mean the necessary command "load_avg" is not available? If yes, why does Linux Dash not check if those commands are available. I miss a "is shell_exec()"-available check as well. Its more clear for the user.

**Comment by afaqurk** [comment]
I will try to address your concerns individually.

>But I don't know if all necessary linux commands are available.

Linux Dash always assumes a that only bare Linux commands are available and try to use them. Unless you have gone out of your way to disable or remove a package, this should not be the concern. If a specific command was unavailable, it would be easy to debug as it would show up as the server response when PHP calls the bash file.

>Does it mean the necessary command "load_avg" is not available. I miss a "is shell_exec()"-available check as well. Its more clear for the user.

No. What you are referring to is the name of the bash file which looks at '/proc/loadavg' to get system stats about average CPU load. This is a Linux file which allows the system to show current load_avg data. So, all Linux Dash is doing is reading that file out. Similar low-level methods of gathering the data are used for most of the data from the Kernel. Unless something is *seriously* off about your Linux installation, you'll have a '/proc/laodavg' file.

>why does Linux Dash not check if those commands are available

Linux Dash was built by a community of smart people. There is probably a good reason for what the code is doing and what is is not. That being said, if you believe there is a better way to write it, I encourage you to submit a Pull Request. I really mean it, please submit code if you think it can be done better.

>I tried to load http://www.example.com/admin/monitor/server/?module=load_avg but it displayed an empty page.

This can be one of a numerous issues with your installation. Support questions are welcomed and addressed by the community on the [Linux Dash Gitter](https://gitter.im/afaqurk/linux-dash).

**Comment by mgutt** [comment]
"If a specific command was unavailable, it would be easy to debug as it would show up as the server response when PHP calls the bash file."

I know how to check that because I'm a developer, but a general user will only see a never ending loading dashboard and thinks "hmm linux dash seems to be buggy".

I suggest the following:
1.) build in a check if necessary PHP shell functions are available
2.) replace the shell call on "modules/shell_files/load_avg" by http://php.net/manual/de/function.sys-getloadavg.php
3.) if the api returns an empty result, javascript should not abort because of an error, it should display in the specific monitor an error message instead. By that the monitor will not be disrupted if one API call fails because of a temporary internet connection problem, too.

P.S. the API returns an empty message because my user is not allowed to access "modules/shell_files/load_avg". This is a not changeable limitation of my hosting company.

Thank you for your invitation to submit a code, but I do not have enough spare time at the moment.
