### ISSUE TITLE
upload and download inverted ?

### ISSUE THREAD

**Issue by arnaudbey** [afaqurk/linux-dash#308]
It seems that upload and download charts are inverted. Upload one shows download and the download one shows upload.

Anyway, I hadn't tried linuxdash for some month and the tool has been improved hard :+1: )

**Comment by afaqurk** [comment]
Well, that was embarrassing. Thanks for catching that! 

There is so much more I wish I had time to add to Linux Dash.

**Comment by arnaudbey** [comment]
No problem :hamster:
