### ISSUE TITLE
cpu load requires core detection

### ISSUE THREAD

**Issue by djtm** [afaqurk/linux-dash#311]
In my case, the script detects "0" cores. Hence it can't calculate load_avg.
As a second best option I propose:

[ $numberOfCores = "0" ] && numberOfCores=1

It's certaintly not 0, let's assume 1.

My cpuinfo
```
Processor       : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 99.26
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc08
CPU revision    : 2

Hardware        : herring
Revision        : 0034
```

**Comment by afaqurk** [comment]
That sounds very reasonable to me. I've added the following: https://github.com/afaqurk/linux-dash/blob/master/server/modules/shell_files/load_avg.sh#L4-L6
