### ISSUE TITLE
Add MQTT features

### ISSUE THREAD

**Issue by xianlin** [afaqurk/linux-dash#315]
Possible to add MQTT features to publish server cpu,ram,application status to a MQTT broker so multiple clients can subscribe to the server messages?

So if used for a Data Center, many servers will be easily monitored by developing a client side application which listent to the server topics and do the data processing (real time display and logging).

**Comment by afaqurk** [comment]
I'm sure it is but I don't know anything about MQTT. However, it is super easy to hook into each Linux Dash request. 

If you would like to submit a pull request at least attempting an integration, I'm sure the community of developers would love to help maintain it. I will also leave this issue open for a while in case someone else want to help develop an MQTT integration branch.
