### ISSUE TITLE
Incorrect RAM Usage 

### ISSUE THREAD

**Issue by shahamit** [afaqurk/linux-dash#321]
I installed this dashboard on my "Oracle Linux Server release 6.4 (Red Hat Enterprise Linux Server release 6.4 (Santiago)" vm and see a big difference in the RAM usage shown by the dashboard when compared with the "top" command output.

![Output of top command](http://i.imgur.com/BUgrS6N.png)
![Linux Dashboard RAM usage](http://i.imgur.com/zEfH2HB.png)

Total RAM being 16 gb, the top command shows that only 4 GB is free while the dashboard shows 15 GB is free.
What could I be missing?

**Comment by vernes** [comment]
I hope this will help

http://serverfault.com/a/379392

**Comment by shahamit** [comment]
Ok. So you are referring to the point that the linux kernel is using up the available RAM but it would be free when the processes need it. The ```free -m``` command output for "-/+ buffers/cache" is match up with the numbers shown on the dashboard.

**Comment by afaqurk** [comment]
@shahamit we have gone back and forth on fixing this issue. And each time, it seems like it is a version of the ```free``` command which we are accounting for.

Could you please tell us your OS flavor, version, and output of ```free --version```. I can investigate with a VM with similar specs to debug.
