### ISSUE TITLE
CPU Load over 100%?

### ISSUE THREAD

**Issue by DerAtrox** [afaqurk/linux-dash#325]
Hey, 
i noticed, that the CPU Load is sometimes over 100%. Is this normal or a bug? 
I'm using linux-dash on a v-server with Debian 7.8 Wheezy.

DerAtrox

**Comment by afaqurk** [comment]
Not at all. Let's debug.

Linux Dash calculates Average CPU Load by dividing the output of loadavg command by the number of CPU cores on your server. You can see the [simple calculation here](https://github.com/afaqurk/linux-dash/blob/master/server/modules/shell_files/load_avg.sh#L8). 

I suspect that this has to do with what your server is reporting as the number of cores. Can you check the **Basic Info** tab and check the **CPU INFO** module. There is a **CPU(s)** line which shows the number of cores on your server. What does it report for you?

**Comment by DerAtrox** [comment]
CPU(s) returns 1.
I'm using linux-dash with PHP on an Apache 2 server.
Last time i looked at your demo page, the CPU Load was also over 100%.

**Comment by afaqurk** [comment]
You're right. I just stress tested the demo server and it showed > 3,000% utilization. Which, as you can imagine, is not how I understood the calculation to work.

I will mark this as a bug and do some research.

If anyone can help shed light onto how to calculate a % utilization (out of 100%) for Linux, please do enlighten me.

Thanks for bringing up the issue.

**Comment by DerAtrox** [comment]
Thank you! :)

**Comment by afaqurk** [comment]
So it seems that the solution to this is relatively simple. 

First, for the sake of clarity, the current CPU Load shows [average cpu load](http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages), which, in Linux, is a very [different concept from % of CPU utilization](http://www.howtogeek.com/194642/understanding-the-load-average-on-linux-and-other-unix-like-systems/). 

However, I had intended it to show CPU utilization.

Resolution:
* The current **CPU Load** module will be renamed to **CPU Avg Load** to sync with Linux system terminology 
* A new module will be added called **CPU Utilization**
  * It will be a single-line graph which shows current CPU utilization
 * It will be an ephemeral value
  * The value will be a percentage between 0 & 100
  * The value will reflect the same value found in the `%Cpu(s)` line of ` top` command
  * Possible equation: ` = 100 - (idle CPU % from top command)` 

I will take a shot at this next time I have a moment to code. Others are welcome to attempt and submit a PR too.

**Comment by afaqurk** [comment]
Please try the most recent update for the changes.
