### ISSUE TITLE
Network Connections Causes Chrome To Hang

### ISSUE THREAD

**Issue by kitedevelopment** [afaqurk/linux-dash#327]
Firefox has no issue but in chrome (latest version) it hangs.

**Comment by afaqurk** [comment]
The [demo ](http://linuxdash.afaqtariq.com/) works fine for me in Chrome 44.0.2403.157 m. Can you provide more details about what exactly in the UI is hanging? Could it be network latency or the system can't handle the polling that is occurring per second?

**Comment by afaqurk** [comment]
@kitedevelopment any update?
