### ISSUE TITLE
is it accurate?

### ISSUE THREAD

**Issue by lorvent** [afaqurk/linux-dash#329]
I really liked it but when i compare charts provided by DigitalOcean and linux-dash.... values are highly different.

linux-dash shows CPU usage is 70%+
DigitalOcean shows CPU usage is ~4%

i don't know which one to believe

**Comment by afaqurk** [comment]
I'm not sure why you're seeing such varying results. The [linux-dash demo](http://linuxdash.afaqtariq.com/#/system-status) is also hosted on DigitalOcean and the graphs relatively match. DigitalOcean shows 6% and the demo shows 5%.

Are you able to confirm which one is correct by seeing the output of `top` command on the server?

**Comment by lorvent** [comment]
from linux-dash
````
24325	root	0.2	3728	7420	bash
24312	root	0	3456	11360	sshd
24509	www-data	0.2	7096	113760	apache2
25220	root	3	3224	9992	sshd
````
from ````top````` command

````
25637 root      20   0 10224 3368 2544 S    2  0.2   0:00.21 sshd
24508 www-data  20   0  113m  17m 9.9m S    1  0.9   0:00.19 apache2
25140 www-data  20   0  112m  15m 8732 S    1  0.8   0:00.10 apache2
24509 www-data  20   0  111m 7104 2080 S    1  0.3   0:00.24 apache2
23948 root      20   0     0    0    0 S    0  0.0   0:00.13 kworker/0:2
24384 root      20   0  2816 1172  936 R    0  0.1   0:00.33 top
````

I am not sure whether you are asking for this info or not but i am ready to debug more.

**Comment by afaqurk** [comment]
@lorvent : no, I meant the system load line of `top` output. It is usually found on the 3rd line and starts with "CPU(s)".

The 4th number in that row shows CPU idle %. It should be a number followed by a percentage sign and " id". That is the percentage of CPU which is not being utilized. That number + the Linux dash number should roughly equal 100.

You can see it here: ![](http://3.bp.blogspot.com/-GWInIvuzs7Q/T-xpyn03cWI/AAAAAAAAEgY/ihpWGimo5qw/s1600/top-ubuntu.png)

**Comment by afaqurk** [comment]
@lorvent any updates?

**Comment by lorvent** [comment]
hi, sorry for delay

idle : 96.3%
as per linux-dash: 

1_min_avg	36.5 %
5_min_avg	16.5 %
15_min_avg	10 %

**Comment by afaqurk** [comment]
@lorvent do you have the most recent copy of Linux dash? 

Because it seems like you are comparing average load module to cpu utilization. These are not compatible measurements. 

Please see #325 for details. Short version: update Linux dash and you'll see 2 cpu graphs: one showing utilization and another showing cpu avg load.

**Comment by lorvent** [comment]
Hi,
i just updated and YES, i see those two now.

CPU utilization matching with graphs in DO...

**Comment by afaqurk** [comment]
Awesome. Glad those graphs are matching now.
