### ISSUE TITLE
CentOS release 6.7 can't show general info

### ISSUE THREAD

**Issue by weibangtuo** [afaqurk/linux-dash#334]
https://github.com/afaqurk/linux-dash/blob/master/server/modules/shell_files/general_info.sh#L16
    lsb_release -a
    LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
    Distributor ID:	CentOS
    Description:	CentOS release 6.7 (Final)
    Release:	6.7
    Codename:	Final

lsb_release -ds echo ```"CentOS release 6.7 (Final)"```. The response data is error JSON, because the double quotation.

**Comment by afaqurk** [comment]
Thanks for bringing this up.

Please pull down the latest version for the fix.
