### ISSUE TITLE
Chart not display well

### ISSUE THREAD

**Issue by weibangtuo** [afaqurk/linux-dash#335]
http://linuxdash.afaqtariq.com/#/system-status

Chart not display well.

<img width="947" alt="f0956e92-01cd-42ad-845b-15da296ddbe5" src="https://cloud.githubusercontent.com/assets/4394281/10361653/1642a882-6ddc-11e5-90ac-86daebae2637.png">

**Comment by afaqurk** [comment]
@weibangtuo Are you saying that this happens on the [Linux Dash demo](http://linuxdash.afaqtariq.com/#/system-status)? I do not see any issues on the demo when I visit it.

**Comment by weibangtuo** [comment]
Windows is OK, but it's not work for Mac OS X. I try Chrome, Firfox and Safari, all display not well.

**Comment by afaqurk** [comment]
@weibangtuo could you open the Console tab in chrome dev tools in Mac OSX? It would be helpful to see if any errors are present as well.

I'll try to find a way to test this on OSX.

**Comment by weibangtuo** [comment]
Only network error: "GET http://linuxdash.afaqtariq.com/websocket 404 (Not Found)".
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by afaqurk** [comment]
Thanks. That network error is a normal status check for websocket support.

Seems like the problem needs to be explored further. Any further info / help would be appreciated.

**Comment by weibangtuo** [comment]
Retina screen trigger this issue.  `smoothie.js` did not deal with Retina screen. We can give `width` and `height` attr to `canvas` element to solve this issue.

**Comment by afaqurk** [comment]
@weibangtuo: I added width and height to inline canvas elements while leaving the CSS which assigns height and width intact.

The code is on [canvas-chart-fix](https://github.com/afaqurk/linux-dash/tree/canvas-chart-fix) branch. I have also pulled that branch on the [demo serve](http://linuxdash.afaqtariq.com/#/system-status)

Can you [try this](http://linuxdash.afaqtariq.com/#/system-status) now? 

To be honest, Retina is not something I want to spend much time addressing. The main goal is regular desktop viewports & tablets.

**Comment by weibangtuo** [comment]
<img width="939" alt="8ad33c0c-4ece-4ecc-8384-393b505a1644" src="https://cloud.githubusercontent.com/assets/4394281/10872949/a11421ec-8147-11e5-83cd-0f9772e6e371.png">
It's OK!

**Comment by afaqurk** [comment]
:+1:
