### ISSUE TITLE
No way to add custom modules / plugin

### ISSUE THREAD

**Issue by JustinAarden** [afaqurk/linux-dash#336]
i can't make my own modules like "show a grep of a string from my syslog)
It just won't display the module. But sometimes is will and i get the next error in my apache errorlog:

sh: 1: dashboard/server/modules/shell_files/grep_ids.sh: not found
(The file has rwxrwrxwx rights (777))

**Comment by afaqurk** [comment]
@JustinAarden : There is a [gitter channel](https://gitter.im/afaqurk/linux-dash) for linux-dash where you can discuss these types of things with other contributors and users live.

Are you sure you have created the `grep_ids.sh` file in the appropriate directory? Also, how are you coding the module on front-end? Did you follow the conventions in `https://github.com/afaqurk/linux-dash/blob/master/js/modules.js` and create your own module definition?
