### ISSUE TITLE
current ram output wrong value

### ISSUE THREAD

**Issue by orumin** [afaqurk/linux-dash#339]
If I use procps-ng ver 3.3.10-, current_ram.sh output is negative value.
cause procps-ng output has changed.

related link: https://bugzilla.redhat.com/show_bug.cgi?id=1158828

**Comment by afaqurk** [comment]
@orumin , thanks for pointing out the incompatibility. 

I will try to address this in next minor release. Feel free to help out with modification of `current_ram.sh` to support `procps-ng version 3.3.10*` via pull request.

**Comment by triforce** [comment]
Is the 'Free' total in Linux-Dash supposed to represent unused memory or memory available for starting new applications?

**Comment by afaqurk** [comment]
@triforce, the "Free" total on *RAM Usage* chart shows memory available for starting new applications.

It aims to be the [MemAvailable](https://www.kernel.org/doc/Documentation/filesystems/proc.txt) field from `/proc/meminfo`.

**Comment by afaqurk** [comment]
@orumin : Please try out the latest push to master. 

Linux Dash now directly parses `/proc/meminfo` to get RAM usage statistics. This, hopefully, circumvents all issues with `procps-ng` & `free` versions.

Please let us know if you come across any issues with the latest changes.

**Comment by orumin** [comment]
@afaqurk thank you for your response.
I tried it, and it seems to be nice!
