### ISSUE TITLE
General info issue in openSUSE Leap 42

### ISSUE THREAD

**Issue by CAI79** [afaqurk/linux-dash#344]
`/usr/bin/lsb_release -ds;/bin/uname -r | sed -e 's/^"//' -e 's/"$//'` command from general_info.sh return 2 lines:
"openSUSE Leap 42.1 (x86_64)"
4.1.12-1-default

we have extra quotes in json:
{ "OS": ""openSUSE Leap 42.1 (x86_64)" 4.1.12-1-default", ...

I suggest to change command to /usr/bin/lsb_release -ds | sed -e 's/^"//' -e 's/"$//';/bin/uname -r or something like this. It works in my case.

**Comment by afaqurk** [comment]
@CAI79 : The `sed` pipe should already be removing any double quotes generated by  `/usr/bin/lsb_release -ds;/bin/uname -r`.

For example, if we run the following in `bash`

```shell
$ echo "openSUSE Leap 42.1 (x86_64)" 4.1.12-1-default | sed -e 's/^"//'  -e 's/"$//'
```

It generates:

```shell
openSUSE Leap 42.1 (x86_64) 4.1.12-1-default
```

Can you please share the output of the following command from your server? 
 ```shell 
/usr/bin/lsb_release -ds 
```

**Comment by afaqurk** [comment]
Please pull down latest commit for fix. General Info module was tested to work on **openSUSE Leap 42.1**.

You can see the [changes here](https://github.com/afaqurk/linux-dash/commit/55140a7e01f5dd4993aa9f0daec08c7b53506fb0#diff-676804d9821d22fadaa6cb01d2e0c6eb). Essentially a modified version of your recommendation.

Thanks for bringing up the issue.

Also, I had no idea that openSUSE Leap had such an awesome interface. Seriously considering switching.

**Comment by CAI79** [comment]
Thanks!
Sorry for delay, it was a deep night and I gone to bed =)

As I can see, You don't need my server's output anymore...

New version shows info correctly.

P.S. openSUSE my favorite distro, glad You liked it =)
