### ISSUE TITLE
'Old' view UI issues

### ISSUE THREAD

**Issue by triforce** [afaqurk/linux-dash#345]
Please see UI issues found when using the 'old' UI settings options:

![linuxdashold](https://cloud.githubusercontent.com/assets/1353074/11035984/901d7fc2-86ed-11e5-9eff-9303056c496a.png)

Running on Chrome 46.0.2490.80 m

**Comment by afaqurk** [comment]
@triforce what screen resolution are you running that on? And are you zoomed in/out at all on the page by any chance?

I was not able to replicate the issue. This is what I see on the [demo](http://linuxdash.afaqtariq.com/#/system-status) and when running linux-dash locally:

![linux-dash-screenshot-old-theme](https://cloud.githubusercontent.com/assets/751323/11054079/c06a6354-872c-11e5-965f-071f1dc6836a.png)

**Comment by triforce** [comment]
Screen resolution 1280 x 1024. No zoom on the browser (i.e at 100%).

**Comment by afaqurk** [comment]
Still not able to replicate the issue. It was checked in `Chrome Version 46.0.2490.80` on Windows 7 & Ubuntu 14.04. I also checked against `Firefox version 42.0` on both operating systems.

Are you on the latest commit of master branch?

At this point, I would need more information on how to duplicate your issue. Would you be able to provide a link to your linux dash instance, either privately via email or here, so I can help debug?

If not, I am open to any other suggestions you might have to replicate your issue.

**Comment by triforce** [comment]
I have done a fresh install and it's absolutely fine now. Closing.

**Comment by afaqurk** [comment]
:+1:
