### ISSUE TITLE
Add IO graph

### ISSUE THREAD

**Issue by Nefelim4ag** [afaqurk/linux-dash#347]
#237 - add the iostat output, but as i see, this is not a realtime values, just output of iostat, i.e. values from system start

Can you please add a more realtime values, if possible in graphs like CPU/Ram usage?

Thank

**Comment by afaqurk** [comment]
@Nefelim4ag, I have no plans to add real-time iostate widget. However, pull requests are welcome.

**Comment by theburn** [comment]
@Nefelim4ag  you can try it #485
