### ISSUE TITLE
swap.sh script does not work if no swap

### ISSUE THREAD

**Issue by j75** [afaqurk/linux-dash#351]
If
```
cat /proc/swaps
Filename				Type		Size	Used	Priority
```
then
```
linux-dash/server/modules/shell_files/swap.sh: line 5: -1: substring expression < 0
```

**Comment by alozovskoy** [comment]
@afaqurk 

I can't reproduce this on previous version (before 968ca538d3d48d898934e33ef5acac9d89f1cb0f):

```
$ sudo swapoff -a
$ cat /proc/swaps 
Filename				Type		Size	Used	Priority
$ ./swap.sh
[ ]
$ sudo swapon -a
$ ./swap.sh 
[ { "filename": "/dev/sda5", "type": "partition", "size": "5105660", "used": "0", "priority": "-1"} ]
$
```

I think @j75 have problem with "priority" with his environment. @j75, what kind of awk you are used? I tried gawk 4.0.2, gawk 4.1.3 and mawk 1.3.3 - all worked  well.

**Comment by afaqurk** [comment]
@alozovskoy , that commit already has the fix. You'll need to go one commit further behind to reproduce the issue.

I was able to recreate the issue and see the same error as @j75
