### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by lgwapnitsky** [afaqurk/linux-dash#352]
are there plans on how to write new widgets for the dashboards and extra pages?

thank you,

**Comment by palumbo** [comment]
We're planning on doing a number of tutorials to show the versatility of the Filestack platform. We'll definitely touch on a number of ways to integrate the picker into your page, including how to implement and customize widgets.

**Comment by afaqurk** [comment]
Good question. There have always been plans for it but it has been one of those things that has fallen on the back-burner. However, I do not see it in the immediate future unless someone submits a PR to add it.

The current wiki gives an overview of the stacks. If you have any specific questions about the setup of the app internals, feel free to ask on the [gitter channel](gitter.im/afaqurk/linux-dash).
