### ISSUE TITLE
Sound Notification 

### ISSUE THREAD

**Issue by anthonyjoddie** [afaqurk/linux-dash#362]
Just a suggestion, I think will be nice if there's a user configured sound or any notification. Example user can set alarm when CPU load average above 50%.

**Comment by joeygallegos** [comment]
Great idea, totally agree with this. Would be a great feature to add especially for when you're monitoring for an event.

**Comment by triforce** [comment]
I agree, a great idea. This might be worth investigating:- https://danielstern.github.io/ngAudio/

**Comment by afaqurk** [comment]
I do not think audio is a good idea for a modern webapp user experience. 

Notifications for certain thresholds is a great idea.  But outside of the scope of Linux Dash. 

There are *tons* of tools that already do system monitoring and alerting. Linux Dash's goal is to show an overview of the system at the current moment to a human user. Monitoring and alerting would introduce a feature-set which broadens the scope of responsibility and defy the _simplicity_ of the webapp.
