### ISSUE TITLE
linux-dash on Ready Nas 202 not working after move of logfiles

### ISSUE THREAD

**Issue by roberttropp** [afaqurk/linux-dash#366]
After Netgear support, has moved the logfiles to /data, linux-dash app does not work anymore.
Is there a way to tell linux-dash where it should look for the logfiles ?

Netgear support claims they cannot help anymore, as this is a 3party app.

Best regards 
Robert

**Comment by afaqurk** [comment]
@roberttropp: I have no idea about Nas 202 but I am happy to help you debug.
 
* Which widget in linux-dash are you referring to?
* Do you get a 404 when you load the linux dash page? Or Is it JS errors? Are there any server error logs you can share?
* What exactly has moved to `/data` on your server? The linux-dash installation? Or is it your files?

Also, if you go on our [gitter channel](https://gitter.im/afaqurk/linux-dash), we can chat more rapidly and other folks might also be able to help you debug this.

**Comment by roberttropp** [comment]
None of the widget's showed anything.
But apparently Netgear has solved the problem now, as it seems to be working now.
I think the problem was that the Nas logfiles was moved, and that linux-dash reads these logfiles.

**Comment by afaqurk** [comment]
linux-dash doesn't read any log files so I don't think that was the problem. I'm curious what the issue might have been.

But I am glad to hear that the issue is fixed. 
Cheers.
