### ISSUE TITLE
lm_sensors and hddtemp support.

### ISSUE THREAD

**Issue by stamepicmorg** [afaqurk/linux-dash#372]
It would be cool(no pun intended) to have support of hadrware temperature monitoring utilites like lm_sensors or hddtemp.
Can you add it? Would you accept a pull request you are not interested in implementing it yourself?

_p.s. - Sorry for my bad English._

**Comment by afaqurk** [comment]
I will not be adding it. However, I think it is a good idea and would welcome anyone who submits a pull request for it.

See: #13

**Comment by stamepicmorg** [comment]
thanks for reply. i will try to implement it.
