### ISSUE TITLE
Add some another beautiful chart plugin based on c3.js

### ISSUE THREAD

**Issue by xied5531** [afaqurk/linux-dash#379]
C3.js
D3-based reusable chart library, 
http://c3js.org/

We can add the beautiful charts use c3.js. You can find examples on http://c3js.org/examples.html

**Comment by afaqurk** [comment]
Some of these charts are beautiful. Thanks for sharing.

I will keep it in mind when new chart use-cases arise. The donut chart seems like a good fit for the partition sizes info.

**Comment by dwbfox** [comment]
c3js seems a bit outdated in terms of its visuals. Reminds me Google Charts of yesteryear. A better and more aestherically pleasning alternative is ChartJS: http://www.chartjs.org/

**Comment by afaqurk** [comment]
Chart.js is beautiful too. I will keep both libraries in mind when the next use-case comes up.

As always, PRs are encouraged, even for proofs of concept.
