### ISSUE TITLE
Running on a minimal/embedded environment, no web framework (node PHP).

### ISSUE THREAD

**Issue by pauldotknopf** [afaqurk/linux-dash#381]
Does somebody have a web server written in pure C/C++? I'd like to add this to my embedded device for testing/development, but I don't want to add a huge dependency, such as node/php/apache.

**Comment by afaqurk** [comment]
If anyone has done this already, I would strongly encourage and welcome a Pull Request.

Support for mininalistic environments such as embedded devices & systems is very much inline with linux-dash's philosophy and purpose.

**Comment by afaqurk** [comment]
@pauldotknopf I wanted to update you on some progress: Tonight I have added a C server (using mongoose) which supports websockets. 

It is currently on the `v2.0` dev branch and will be released with Linux Dash v2.0.  https://github.com/afaqurk/linux-dash/commit/a41da7333ad30c650ea47924bcc3cab25ca54e54

You can see the compiled binary (fully functional with source on that branch) here: https://github.com/afaqurk/linux-dash/commit/9f8b4ba374c35beddf1e9d4092c9ac08cdd11b1c

The `v2.0` branch is currently stable but not guaranteed to be so always. Feel free to use it at your own discretion.

If you have any suggestions or improvements for that C server, please do let me know.

**Comment by pauldotknopf** [comment]
@afaqurk Thanks! I will take a look at it!

**Comment by afaqurk** [comment]
Another added benefit in linux-dash v2.0: reduced size. Currently, the entire distribution is hovering around 300kb. 

Good news for low-resource environments like embedded devices.

**Comment by afaqurk** [comment]
This has been fully implemented in `v2.0` release branch. You can see the preview here: https://github.com/linux-dash/linux-dash and here: https://linux-dash.github.io

I will be marking this issue closed soon.
