### ISSUE TITLE
current_ram.sh free memory is not correct

### ISSUE THREAD

**Issue by maozi07** [afaqurk/linux-dash#386]
```
echo $memInfo | $awkCmd '{print "{ \"total\": " ($2/1024) ", \"used\": " ( ($2-($5+$8+$11))/1024 ) ", \"free\": " (($5+$8+$11)/1024) " }"  }'
```
free shoud be only \$5 not the sum of 5 8 11

**Comment by afaqurk** [comment]
Linux Dash reports non-buffered RAM. ( #321 ) 

There is a reason for adding the buffer & cached ram output from `/proc/meminfo/` to "free":

Source: http://serverfault.com/a/379392

> The short story is that the Linux kernel gobbles up RAM as it is available to use for disk caching. There's nothing you can do about it...
> The RAM is really there and free for processes to use at their whim. That's what's meant by the -/+ buffers/cache: row in free -m

**Comment by maozi07** [comment]
I known，but free and available are different，it's not good show rong message to user

**Comment by afaqurk** [comment]
Good point. I'll update the text "Free" to "Available"
