### ISSUE TITLE
[FIX] Internet speed test stopped working

### ISSUE THREAD

**Issue by muessigb** [afaqurk/linux-dash#392]
Please replace the speedtest-cli.py with the latest version found here:
https://github.com/sivel/speedtest-cli

It worked fine, after replacing the old script with the new version.

**Comment by afaqurk** [comment]
Have a look at the [v2.0 branch](https://github.com/afaqurk/linux-dash/tree/v2.0). This future release of Linux Dash will be removing speedtest implementation altogether.
