### ISSUE TITLE
Time in 24hr format

### ISSUE THREAD

**Issue by meauses** [afaqurk/linux-dash#395]
Is it possible to create the option to display the time and dates in a personally defined (e.g. 24hr  dd-mm-yyyy) format?

**Comment by meauses** [comment]
Timestamp can be changed in the last-update.html file.
If you replace; 
<span ng-show="timestamp">{{ timestamp | date:'hh:mm:ss a' }}</span>
with;
<span ng-show="timestamp">{{ timestamp | date:'HH:m:s' }}</span>

You will have time in 24 hour format.

Not yet that familiar with pull requests or nodejs, so thats why i've added part of the solution here.

**Comment by afaqurk** [comment]
Please see your PR for comments.
