### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by christophetd** [afaqurk/linux-dash#404]
From the readme : 

> Step 2: Secure Linux Dash
> Linux Dash does not provide any security or authentication features.

I don't think that's enough to make people secure their installation. Considering the number of potential users this may affect, I am willing to write a small tutorial explaining how to use nginx as a reverse proxy with basic auth to access linux-dash. Would you include it in the readme, @afaqurk ?

**Comment by 3ddysan** [comment]
I've added [basic-auth](https://www.npmjs.com/package/basic-auth) to server/index.js on my privat server.
`
var auth    = require('basic-auth');

app.use(function(req, res, next) {
  var user = auth(req);
  if (!user || "USERNAME" !== user.name || "SECRET" !== user.pass) {
    res.set('WWW-Authenticate', 'Basic realm="Prohibited"');
    return res.status(401).send();
  }
  return next();
});
`

**Comment by afaqurk** [comment]
@christophetd I appreciate the thought. And this same exact thing has been brought up many times by community contributors, so you're not alone.

However, I have given this thorough thought and stick by the decision to not provide any security measures built into Linux Dash. Providing even an iota of default security behavior is giving a false sense of security for the application unless it is backed by thorough support and more than one, mature, researched solution. Unfortunately, Basic Auth (or any simple password protection) is not that solution. I would rather Linux Dash focus on what it does best and leave everything else up to better, more focused solutions.

However, you have brought up something that is a fair point: 
> I don't think that's enough to make people secure their installation.

Maybe the warning in the README needs to be more prominent and clear. Let me know if you have any contributions or thoughts on that.

**Comment by christophetd** [comment]
Hey, thanks for your answer.

>  I would rather Linux Dash focus on what it does best and leave everything else up to better, more focused solutions.

I totally understand and respect that. My proposal was to include in the README a link to a tutorial like « _adding basic authentication to linux-dash with nginx_ », so that the users have a ressource to set it up easily. I can write this tutorial since it is quite easy to do and I have already done it.

Let me know if it sounds good.

**Comment by PrzemekSkw** [comment]
> I've added [basic-auth](https://www.npmjs.com/package/basic-auth) to server/index.js on my privat server.
> 
> ```js
> var auth    = require('basic-auth');
> 
> app.use(function(req, res, next) {
>   var user = auth(req);
>   if (!user || "USERNAME" !== user.name || "SECRET" !== user.pass) {
>     res.set('WWW-Authenticate', 'Basic realm="Prohibited"');
>     return res.status(401).send();
>   }
>   return next();
> });
> ```

Hello, I add that to my linux-dash installation but I don't have any password prompt. I can open my Linux-Dash Panel without any credentials.
I only change USERNAME to my_username and SECRET to my_original_password. Then I: `npm install basic-auth`.
Any other steps I need to do? 

Regards.
