### ISSUE TITLE
WebSocket connection fails on Safari 

### ISSUE THREAD

**Issue by Dima4ka** [afaqurk/linux-dash#406]
WebSocket connection fails with code 401 on Safari (tested on macOS Sierra Safari Version 10.0.1 (12602.2.14.0.1) and iOS 10 Safari)

WebSocket connection to 'wss://my.domain.com' failed: Unexpected response code: 401

My site use HTTPS with LetsEncrypt certificate and NGINX proxy.

Interestingly, everything works perfectly on Google Chrome.

It may be that the bug is on the Apple's side, but I will open an issue anyway.

**Comment by masaykh** [comment]
hm it is connection without port ?
i mean should not it be wss://my.domain.com:555 ?
maybe safari need explict port definnition

**Comment by Dima4ka** [comment]
Maybe.

I am not an expert on WebSockets, but I certainly do not allowing connections on ports other than 80 or 443, so I would assume the port definition is unnecessary (it should default to 443 in the case of https).

Anyway, were you able to verify the issue on Safari?

**Comment by afaqurk** [comment]
@Dima4ka While this issue does surprise me, please be aware that Safari is neither explicitly supported nor a target browser for Linux Dash.

Have you tried any other web browser?

Happy to leave the issue open to see if someone else in the community can provide help.
