### ISSUE TITLE
Upload and Download transfer rates values

### ISSUE THREAD

**Issue by gklipel** [afaqurk/linux-dash#409]
Hi!

Just a question, it was not supposed to be the TX and RX bytes sided with iface name in Network session?

download_transfer_rate.sh and upload_transfer_rate.sh scripts returns values correctly, but on web frontend they don't.

This is right?

Thanks in advance!

**Comment by afaqurk** [comment]
@gklipel Thanks for posting the issue. Can you provide more detail?

* What are you seeing on the front-end?
* What specific type of discrepancy are you seeing? Is it a delay? Is it a difference of exactly X order of magnitude?
* How are you verifying either end's correctness?

With that information, I might be able to understand the problem better.
