### ISSUE TITLE
Elasticsearch  running but not displaying

### ISSUE THREAD

**Issue by phpmind** [afaqurk/linux-dash#412]
Hello, 

Elasticsearch  running inside ubuntu  16 but not displaying in the "RAM INTENSIVE PROCESSES" list.
It's shows only java. 
Elastic run on port :9200

Very happy with utility. 

Thanks

**Comment by afaqurk** [comment]
@phpmind Interesting. I believe this is an issue with how Elasticsearch is registered as a process with the OS. It shows as Java bc it is, technically, a Java runtime application.

Linux Dash is simply reporting what your OS provides it: https://github.com/afaqurk/linux-dash/blob/master/server/modules/shell_files/ram_intensive_processes.sh

Hope that makes sense. If you find there to be more information which can show Linux Dash not reporting what your OS is, please reopen the issue.
