### ISSUE TITLE
Link "Linux Dash v2.0" in README.md is broken

### ISSUE THREAD

**Issue by Djailla** [afaqurk/linux-dash#415]
All is in the title ;)

"Linux Dash v2.0" is pointing to :
https://linux-dash.github.io/docs/#getting-started

**Comment by triforce** [comment]
The whole linux-dash github site isn't up, not just one link.

**Comment by afaqurk** [comment]
@Djailla I've removed that entire paragraph for now. V2.0 never got released and certainly isn't ready to be yet.

@triforce That organization was deleted. I'll try to migrate those assets over to a github pages for this repo.
