### ISSUE TITLE
Is not working in nodejs

### ISSUE THREAD

**Issue by johnfelipe** [afaqurk/linux-dash#416]
felipe@unidadproyectosnacionales:~$ git clone https://github.com/afaqurk/linux-dash.git
	Cloning into 'linux-dash'...
	remote: Counting objects: 4209, done.
	remote: Total 4209 (delta 0), reused 0 (delta 0), pack-reused 4209
	Receiving objects: 100% (4209/4209), 4.50 MiB | 0 bytes/s, done.
	Resolving deltas: 100% (2465/2465), done.
	Checking connectivity... done.
	felipe@unidadproyectosnacionales:~$ cd linux-dash/
	felipe@unidadproyectosnacionales:~/linux-dash$ npm install

	> websocket@1.0.24 install /home/felipe/linux-dash/node_modules/websocket
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/home/felipe/linux-dash/node_modules/websocket/build'
	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
	  COPY Release/bufferutil.node
	  CXX(target) Release/obj.target/validation/src/validation.o
	  SOLINK_MODULE(target) Release/obj.target/validation.node
	  COPY Release/validation.node
	make: Leaving directory `/home/felipe/linux-dash/node_modules/websocket/build'
	linux-dash@1.2.0 /home/felipe/linux-dash
	├─┬ express@4.14.1
	│ ├─┬ accepts@1.3.3
	│ │ ├─┬ mime-types@2.1.14
	│ │ │ └── mime-db@1.26.0
	│ │ └── negotiator@0.6.1
	│ ├── array-flatten@1.1.1
	│ ├── content-disposition@0.5.2
	│ ├── content-type@1.0.2
	│ ├── cookie@0.3.1
	│ ├── cookie-signature@1.0.6
	│ ├─┬ debug@2.2.0
	│ │ └── ms@0.7.1
	│ ├── depd@1.1.0
	│ ├── encodeurl@1.0.1
	│ ├── escape-html@1.0.3
	│ ├── etag@1.7.0
	│ ├─┬ finalhandler@0.5.1
	│ │ ├── statuses@1.3.1
	│ │ └── unpipe@1.0.0
	│ ├── fresh@0.3.0
	│ ├── merge-descriptors@1.0.1
	│ ├── methods@1.1.2
	│ ├─┬ on-finished@2.3.0
	│ │ └── ee-first@1.1.1
	│ ├── parseurl@1.3.1
	│ ├── path-to-regexp@0.1.7
	│ ├─┬ proxy-addr@1.1.3
	│ │ ├── forwarded@0.1.0
	│ │ └── ipaddr.js@1.2.0
	│ ├── qs@6.2.0
	│ ├── range-parser@1.2.0
	│ ├─┬ send@0.14.2
	│ │ ├── destroy@1.0.4
	│ │ ├─┬ http-errors@1.5.1
	│ │ │ ├── inherits@2.0.3
	│ │ │ └── setprototypeof@1.0.2
	│ │ ├── mime@1.3.4
	│ │ └── ms@0.7.2
	│ ├── serve-static@1.11.2
	│ ├─┬ type-is@1.6.14
	│ │ └── media-typer@0.3.0
	│ ├── utils-merge@1.0.0
	│ └── vary@1.1.0
	└─┬ websocket@1.0.24
	  ├── nan@2.5.1
	  ├─┬ typedarray-to-buffer@3.1.2
	  │ └── is-typedarray@1.0.0
	  └── yaeti@0.0.6

	felipe@unidadproyectosnacionales:~/linux-dash$ node server/
	Linux Dash Server Started!

How can solved

**Comment by Q-Max** [comment]
What's going to be wrong? The server didn't start? How about add a sudo like in #419 ?

**Comment by afaqurk** [comment]
@johnfelipe Please let us know if you can post more detail or answer @Q-Max's excellent questions. Until then, this request is expired.

**Comment by johnfelipe** [comment]
felipe@unidadproyectosnacionales:~$ sudo rm -r linux-dash/
	felipe@unidadproyectosnacionales:~$ git clone https://github.com/afaqurk/linux-dash.git
	Cloning into 'linux-dash'...
	remote: Counting objects: 4308, done.
	remote: Compressing objects: 100% (54/54), done.
	remote: Total 4308 (delta 26), reused 0 (delta 0), pack-reused 4253
	Receiving objects: 100% (4308/4308), 4.52 MiB | 0 bytes/s, done.
	Resolving deltas: 100% (2523/2523), done.
	Checking connectivity... done.
	felipe@unidadproyectosnacionales:~$ cd linux-dash/
	felipe@unidadproyectosnacionales:~/linux-dash$ sudo npm install

	> websocket@1.0.24 install /home/felipe/linux-dash/node_modules/websocket
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/home/felipe/linux-dash/node_modules/websocket/build'
	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
	  COPY Release/bufferutil.node
	  CXX(target) Release/obj.target/validation/src/validation.o
	  SOLINK_MODULE(target) Release/obj.target/validation.node
	  COPY Release/validation.node
	make: Leaving directory `/home/felipe/linux-dash/node_modules/websocket/build'
	linux-dash@1.2.0 /home/felipe/linux-dash
	├─┬ express@4.15.2
	│ ├─┬ accepts@1.3.3
	│ │ ├─┬ mime-types@2.1.15
	│ │ │ └── mime-db@1.27.0
	│ │ └── negotiator@0.6.1
	│ ├── array-flatten@1.1.1
	│ ├── content-disposition@0.5.2
	│ ├── content-type@1.0.2
	│ ├── cookie@0.3.1
	│ ├── cookie-signature@1.0.6
	│ ├─┬ debug@2.6.1
	│ │ └── ms@0.7.2
	│ ├── depd@1.1.0
	│ ├── encodeurl@1.0.1
	│ ├── escape-html@1.0.3
	│ ├── etag@1.8.0
	│ ├─┬ finalhandler@1.0.1
	│ │ ├── debug@2.6.3
	│ │ └── unpipe@1.0.0
	│ ├── fresh@0.5.0
	│ ├── merge-descriptors@1.0.1
	│ ├── methods@1.1.2
	│ ├─┬ on-finished@2.3.0
	│ │ └── ee-first@1.1.1
	│ ├── parseurl@1.3.1
	│ ├── path-to-regexp@0.1.7
	│ ├─┬ proxy-addr@1.1.3
	│ │ ├── forwarded@0.1.0
	│ │ └── ipaddr.js@1.2.0
	│ ├── qs@6.4.0
	│ ├── range-parser@1.2.0
	│ ├─┬ send@0.15.1
	│ │ ├── destroy@1.0.4
	│ │ ├─┬ http-errors@1.6.1
	│ │ │ └── inherits@2.0.3
	│ │ └── mime@1.3.4
	│ ├── serve-static@1.12.1
	│ ├── setprototypeof@1.0.3
	│ ├── statuses@1.3.1
	│ ├─┬ type-is@1.6.14
	│ │ └── media-typer@0.3.0
	│ ├── utils-merge@1.0.0
	│ └── vary@1.1.1
	└─┬ websocket@1.0.24
	  ├── nan@2.5.1
	  ├─┬ typedarray-to-buffer@3.1.2
	  │ └── is-typedarray@1.0.0
	  └── yaeti@0.0.6

	felipe@unidadproyectosnacionales:~/linux-dash$ sudo node server/
	Linux Dash Server Started on port 8080!

still not working

**Comment by afaqurk** [comment]
@johnfelipe That still doesn't provide us with enough information. What is not working? Are you not able to see Linux Dash webpage at `http://localhost:8080` in your browser?
