### ISSUE TITLE
is not working in php7 + nginx

### ISSUE THREAD

**Issue by johnfelipe** [afaqurk/linux-dash#417]
![pantallazo-0107](https://cloud.githubusercontent.com/assets/428820/22470060/018959be-e79c-11e6-85ee-acd74f2eb9fc.png)

How solved?

**Comment by triforce** [comment]
Please post software versions, OS type/version and any log files please.

**Comment by afaqurk** [comment]
@johnfelipe Please let us know if you can answer @triforce's question. Until then, this request is expired.
