### ISSUE TITLE
Cannot run node server at a subdir like '/linux-dash'

### ISSUE THREAD

**Issue by junalmeida** [afaqurk/linux-dash#419]

**Comment by Q-Max** [comment]
Maybe you need to add sudo to the head. Like below.

> .../linux-dash$ sudo node server/

**Comment by afaqurk** [comment]
@junalmeida This should be entirely possible as long as you run your web-server at the correct path configuration. We're going to need a bit more detail in order for this to be understood as an issue with linux-dash.
