### ISSUE TITLE
Working with subfolders

### ISSUE THREAD

**Issue by mtx-z** [afaqurk/linux-dash#425]
Hey there !

I'm trying to install the linux-dash in a sub-directory of my apache folder.
I have mydomain.com hosted on my server at /var/www.

I cloned the GIT repo to /var/www/linux-dash/.

If i go to mydomain.com/linux-dash/, i see the demo dashboard working great.

No if i go to mydomain.com/linux-dash/app/, the dashboard is displaying but without data: i see a 404 on /websocket.

My question: what i'm doing is possible ? Or do i need a subdomain that is pointed directly to /app/ ? 

Thanks !

**Comment by nguyenvulong** [comment]
check this out 
/linux-dash/ is a demo version
/linux-dash/app/ is the real one, but you gotta change the code to make it work with php & python for the time being

https://github.com/afaqurk/linux-dash/issues/430

**Comment by afaqurk** [comment]
Try checking out latest from master branch.
