### ISSUE TITLE
SyntaxError: Unexpected token \ in JSON at position 2

### ISSUE THREAD

**Issue by whw3** [afaqurk/linux-dash#427]
Not sure if this variation is needed due to php 7.0, but I keep getting JSON errors until I updated /server/index.php to the followiing 
changed
`echo shell_exec( $shell_file . " " . $module );`
to 
`echo stripcslashes(shell_exec( $shell_file . " " . $module ));`

**Comment by whw3** [comment]
Actual looking at `linux_json_api.sh` it seems the extra quotes are intentional.  Odd, since the php version didn't work until I stripped them out of the returning json data with `stripcslashes()`

**Comment by cyberweasel** [comment]
Thank you!  this helped me to get it working finally!

**Comment by tangowhisky37** [comment]
I was wondering why my dashboards weren't working as well. This is a simple fix.

It's going to impact a lot of people out there and possibly worth integrating into the codebase.

Thanks a ton!!!

**Comment by afaqurk** [comment]
Should be addressed in #443
