### ISSUE TITLE
Dashboard does not fully display system info

### ISSUE THREAD

**Issue by nguyenvulong** [afaqurk/linux-dash#430]
**UPDATE 1:** I am able to make it work by ... runing nodejs
but still it's not working with  php, python

![image](https://user-images.githubusercontent.com/1311412/28081098-1fbdd6a8-66a9-11e7-9a6a-4cbd53d1f6b3.png)
------------------------------

**PREVIOUS post:**
I understand that there are two dashboards:
- demo: located in /linux-dash/ (this one uses static data, I just skipped it and moved on to the real one below)
- real: located in /linux-dash/app/. I access my server URL at : http://myIP/linux-dash/app/

Even though there are requests from module "disk_partitions" like these
![image](https://user-images.githubusercontent.com/1311412/28077897-09fad2c2-669e-11e7-9248-57589b3e648e.png)

But still I got no results displayed on the dashboard
![image](https://user-images.githubusercontent.com/1311412/28077823-c71bb688-669d-11e7-8036-74d55ae31366.png)

I also manually ran the command produced by the shell script successfully
![image](https://user-images.githubusercontent.com/1311412/28078000-5ddb8472-669e-11e7-82ae-f4d87a81859d.png)

Do you have any ideas what need to be corrected here? Thank you!

**Comment by whw3** [comment]
Appears you're having the same issue w/php that I ran into.  If you have a look at my issue report I include a work around.

**Comment by nguyenvulong** [comment]
Nice!
I was able to make index.py (python script) work by doing the same way, so I suspect it's not the problem  of  index.* files in side /app/server/ but the process of handling the return value afterward
Only index.js works without any modification, as it's native to javascript, angularjs scripts

Specifically, it's the problem of "linuxDash.min.js" inside /app directory

Example:
Line 34, I add the backslash stripper:
![image](https://user-images.githubusercontent.com/1311412/28199399-46ee9cd2-68a0-11e7-9c33-dd806e07684d.png)

**Comment by goooooodman** [comment]
/app/server/linux_json_api.sh
Line 5:
`#echo -n "$data" | sed -r "s/\"/\\\\\"/g" | tr -d "\n"; `
====>
`echo $data`

**Comment by afaqurk** [comment]
This should now be addressed (php)

**Comment by j-archit** [comment]
I seem to have the same issue but with nodejs. Tried the fix above, didn't work, can anyone help?
