### ISSUE TITLE
could not load google fonts and angular

### ISSUE THREAD

**Issue by Dysheng** [afaqurk/linux-dash#432]
![image](https://user-images.githubusercontent.com/6174604/29552280-280eecc8-8749-11e7-9d77-f5258a875ef2.png)

**Comment by josephbleroy** [comment]
@dysheng Are you using HTTPS and HTTP headers?

**Comment by Dysheng** [comment]
I just use http.  
I don't whether is the question of China network firewall @josephbleroy
