### ISSUE TITLE
Schedule crontab issue

### ISSUE THREAD

**Issue by eimrsha** [afaqurk/linux-dash#436]
Hi 
I have made changes for the schedule crontab but it's not popping on dashboard, but from the command line i am able to see the values

![image](https://user-images.githubusercontent.com/32432589/31118678-4c8e203e-a83f-11e7-8b4a-f3911155149c.png)
on dash board
![image](https://user-images.githubusercontent.com/32432589/31118708-6995bbce-a83f-11e7-8295-58368da522f3.png)

**Comment by afaqurk** [comment]
Without details, it is difficult to tell what the issue is in this case.

Does the browser's console provide more details?

Please note that Github Issues are not the appropriate forum for support on development questions. Please use the [Gitter Channel](https://gitter.im/afaqurk/linux-dash)
