### ISSUE TITLE
displaying Chart on the webserver

### ISSUE THREAD

**Issue by eimrsha** [afaqurk/linux-dash#437]
Hi All
I have created one customized module and I am able to get output successful on the command line. also if I tried to display, I am not able to create new box window for this module on web server

**Comment by afaqurk** [comment]
Please reference the many existing modules that do this: https://github.com/afaqurk/linux-dash/tree/master/src/js/plugins

If you have additional trouble, you can propose a change to [Contributor's Guide](https://github.com/afaqurk/linux-dash/wiki/Contributor's-Guide) that others can help fill in.
