### ISSUE TITLE
Anti-aliasing. For the lack of a better title

### ISSUE THREAD

**Issue by veganexe** [afaqurk/linux-dash#446]
In few graphs, especially the network graphs, the curves are jagged and off-putting. Anyway to make them render smoothly without any jagged curves?

**Comment by afaqurk** [comment]
Linux Dash uses [smoothie charts](http://smoothiecharts.org/) under the hood. Any changes to how they render would need to be addressed in that library.

Smoothie Charts project GitHub: https://github.com/joewalnes/smoothie/
