### ISSUE TITLE
Daemon always monitoring?

### ISSUE THREAD

**Issue by Ansem93** [afaqurk/linux-dash#456]
Hi everyone! I'm looking for something like linux dash!
Something like this that is light, cool and easy to use.

The only problem is that I want a dashboard that will always monitor the activity of my server, so for example I can see how much ram I used 10 minutes or 6 months ago.

Is it possible to do that? Like saving cpu, ram, network and hdd utilization, cpu temp.. Maybe even every process CPU and ram utilization.

**Comment by afaqurk** [comment]
> Is it possible to do that?
Possible, yes. But Linux Dash isn't built to do that. It has a purposefully limited scope.

There are a plethora of tools and services that are intended to be used this way that are a better fit than Linux Dash.
