### ISSUE TITLE
Disk check module is should be called whenever there is a change in disk space. However, the system is not working in this way

### ISSUE THREAD

**Issue by vibhorejaiswal** [afaqurk/linux-dash#473]

**Comment by vibhorejaiswal** [comment]
Diskcheck module should keep polling for the changes in the disk sizes being monitored. However, the disk size doesn't keep polling and hence manual refresh checks the changes in size of the disks if any.

Can we have a fix to it ?

**Comment by tariqbuilds** [comment]
Events from OS or diffing server-side are not supported. 
It can either be manual or polling ATM
