### ISSUE TITLE
Remove Linux-Dash

### ISSUE THREAD

**Issue by MrJuanBond** [afaqurk/linux-dash#516]
I would like to remove Linux-Dash from my Pi. 

I can not find it in my dpkg listing.

**Comment by akupiec** [comment]
There is no package it's just plain scripts, removal steps would depend how did you installed it :) 

ex.: if you fallowed recommended nodejs steps just stop the process and remove zip file (if present) & "installation" directory....

**Comment by MrJuanBond** [comment]
That makes perfect sense! Thank you!
